name: Build
on: [pull_request, workflow_dispatch]

concurrency:
  group: build-${{ github.event.number }}
  cancel-in-progress: true

jobs:
  cocoapods:
    name: CocoaPods
    runs-on: macos-13
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: bundle install

      - name: Run pod lib lint
        run: bundle exec fastlane build_pod

  spm:
    name: Swift Package Manager
    runs-on: macos-13
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: bundle install

      - name: Build SPM test app
        run: bundle exec fastlane build_spm

  carthage:
    name: Carthage
    runs-on: macos-13
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: bundle install

      - name: Build Carthage test app
        run: bundle exec fastlane build_carthage
